INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Manzana');		-- Frutas
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Pera');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Limón');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Sandía');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Melón');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Papaya');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Albaricoque');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Arándano');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Breva');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Cereza');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Ciruela');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Endrina');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Frambuesa');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Fresa');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Granada');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Grosella');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Higo');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Lima');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Mandarina');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Melocotón');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Membrillo');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Mora');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Naranja');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Níspero');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Piña');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Plátano');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Pomelo');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Uva');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Aguacate');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Alquejenje');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Caqui');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Carambola');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Chirimoya');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Coco');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Guayaba');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Kiwano');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Kiwi');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Kumquat');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Lichi');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Mango');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Mangostán');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Maracuyá');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Papaya');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Pitahaya');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Rambután');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Tamarillo');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Tuna');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Clementina');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Dátil');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Toronja');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Tangerina');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Jaca');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Pasa');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Panapén');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Cantalupo');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Durián');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Longan');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Nectarina');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Durazno');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Zapotillo');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Zapote');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Feijoa');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Jujubo');	-- Hortalizas y verduras
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Cebolla');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Acelga');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Ajo');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Alcachofa');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Apio');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Berenjena');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Repollo');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Borraja');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Brécol');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Calabaza');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Calabacín');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Cardo');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Coles de bruselas');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Col lombarda');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Coliflor');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Endibia');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Escarola');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Espárrago');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Espinaca');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Hinojo');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Judía');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Lechuga');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Nabo');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Pepino');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Pimiento verde');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Pimiento rojo');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Pimiento');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Puerro');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Rábano');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Remolacha');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Seta');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Tomate');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Zanahoria');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Patata');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Nabicol');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Grelo');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Ajedrea');		-- Especias
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Ajenuz');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Ají');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Ajonjolí');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Albahaca');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Alcaravea');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Alholva');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Amapola');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Anís');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Asafétida');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Azafrán');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Cajún');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Canela');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Cardamomo');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Casia');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Chile');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Cilantro');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Citronela');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Clavo');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Comino');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Cúrcuma');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Curri');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Enebro');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Eneldo');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Estragón');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Fenogreco');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Calanga');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Guindilla');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Hierbabuena');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Hierbaluisa');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Jengibre');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Laurel');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Macis');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Masala');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Mejorana');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Melisa');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Menta');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Mostaza');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Neguilla');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Ñora');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Nuez moscada');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Orégano');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Páprika');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Perejil');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Pimentón dulce');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Pimentón picante');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Pimienta blanca');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Pimienta negra');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Pimienta de Sichuán');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Sésamo');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Tamarindo');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Wasabi');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Abadejo');		-- Pescados y mariscos
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Angula');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Anguila');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Arenque');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Atún');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Bagre');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Coporo');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Barbo');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Besugo');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Boquerón');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Bonito');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Caballa');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Catalana');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Carite');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Carpa');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Cazón');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Congrio');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Curbina');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Dorada');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Pez espada');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Esturión');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Gallo');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Lamprea');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Lenguado');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Lebranche');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Lubina');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Lucio');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Mero');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Merluza');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Pescadilla');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Pargo');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Raya');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Rape');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Róbalo');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Rodaballo');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Salmonete');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Salmón');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Sardina');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Sargo');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Sepia');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Pavón');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Tajalí');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Tiburón');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Trucha');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Acedía');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Bacaladilla');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Boga');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Breca');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Burro');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Calamar');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Cantara');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Caramel');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Corvina');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Chapa');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Dentol');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Chirrete');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Espetón');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Estornino');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Faneca');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Fletán');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Galán');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Gallo (pescado)');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Cabracho');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Gallopedro');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Jurel');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Lecha');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Llampua');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Magre');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Maje');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Marrajo');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Mujel');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Palometa');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Platija');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Chipirón');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Sama');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Almeja');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Almendra de mar');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Berberecho');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Bígaro');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Bogavante');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Camarón');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Cañailla');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Carabinero');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Centollo');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Erizo de mar');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Galera');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Gamba');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Gambón');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Langosta');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Langostino');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Lapa');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Mejillón');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Navaja');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Nécora');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Ostra');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Percebe');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Pulpo');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Sepioneta');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Tallarina');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Vieira');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Cigala');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Cangrejo');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Quisquilla');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Buey de mar');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Pota (lura)');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Pasta');			-- Pasta
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Spaghetti');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Tallarín');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Macarrón');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Penne');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Ñoqui');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Ravioli');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Tortellini');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Fideo');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Vermicelli');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Pappardelle');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Fettuccine');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Linguine');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Ziti');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Bucatini');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Rigatoni');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Tortiglioni');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Fusilli');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Rotini');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Farfalle');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Dedales');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Ternera');		-- Carnes
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Chuleta de ternera');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Carne picada (ternera)');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Jarrete de ternera');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Entrecot de ternera');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Carrillera de ternera');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Redondo de ternera');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Costilla de ternera');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Solomillo de ternera');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Chuletón de ternera');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Bistec de ternera');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Lengua de ternera');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Pollo');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Alitas de pollo');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Pechuga de pollo');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Zanco de pollo');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Pavo');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Pechuga de pavo');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Pechuga de pavo');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Zanco de pavo');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Solomillo de cerdo');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Carne picada (cerdo)');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Costilla de cerdo');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Oreja de cerdo');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Zorza');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Lacón');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Hamburguesa');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Albóndigas');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Jamón');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Hígado');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Mano');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Osobuco');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Chorizo');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Salchicha');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Croca');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Entrecot de buey');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Chorizo criollo');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Lomo adobado');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Panceta');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Chuleta de cordero');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Chuletón de buey');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Conejo');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Queso fresco');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Queso semicurado');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Queso curado');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Jamón serrano');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Nata');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Yogurt natural');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Azúcar');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Sal');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Harina');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Huevo');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Leche');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Agua');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Chocolate');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Café molido');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Coco rayado');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Aceite de oliva');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Aceite de girasol');
INSERT INTO ingredients (created_at, updated_at, name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Pan');
